### PR TITLE
add `zapier-scripts`

### PR DESCRIPTION
**Pull request by calebpeterson**

### CODE REVIEW

**Comment by calebpeterson** [comment]
hey @ruebel, got the `zapier-scripts` yak shaved. please give it :eyes: when you have second. if it all looks good, feel free to push the merge button 👍

**Comment by ruebel** [comment]
@calebpeterson 	I think you will need to update the `eslint` and `babel` configs for this to fully use `zapier-scripts`

**Comment by calebpeterson** [comment]
@ruebel it looks like `zapier-scripts` has defaults https://github.com/zapier/zapier-scripts#overriding-configuration-defaults

please let me know if I'm misinterpreting the docs

**Comment by ruebel** [comment]
@calebpeterson that's interesting because I've always seen a `.babelrc` and a `.eslintrc.js` in apps that use `zapier-scripts`

see:

https://github.com/zapier/zapier-ui/blob/master/packages/common-components/.babelrc
https://github.com/zapier/zapier-ui/blob/master/packages/common-components/.eslintrc.js

**Comment by calebpeterson** [comment]
💯 @ruebel I'll get those added... better safe than sorry ¯\_(ツ)_/¯

**Comment by ruebel** [comment]
@calebpeterson I would run `yarn lint` and `yarn format` after making the change to make sure we don't have any new linting errors / format the code.

**Comment by calebpeterson** [comment]
@ruebel  `lint`ed and `format`ed

**Pull request merged**
